include("test_CG.jl")
include("test_CG_memory_vs_disk.jl")
include("test_FFTOp.jl")
include("test_MWNI.jl")
include("test_POCS.jl")
#include("test_SeisLinearEvents.jl")
#include("test_AcousticWave2D.jl")
